### ISSUE TITLE
Validation in reports

### ISSUE THREAD

**Issue by moahmed** [batpad/crveillance-reports#7]
Do not allow user to submit empty report.

Also maybe block submission if video is not paused

**Comment by batpad** [comment]
Todo:
  - Add validation to backend to disallow empty values for title, description
  - Display some validation error on frontend if user tries to submit empty form
  - Disable submit button if video is not paused, only enable when video is paused (does this seem correct?)

**Comment by moahmed** [comment]
Yes that should be easy and fine
